name: Build + Lint
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        node: ['18']
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
